export const ERROR_MESSAGE = {
  EMAIL_ALREADY_EXIST: 'emailAlreadyExist',
  IMAGE_IS_NOT_VALID: 'imageIsNotValid',
  TOPIC_IS_NOT_VALID: 'topicIsNotValid',
  POST_IS_NOT_VALID: 'postIsNotValid',
  PAGE_IS_NOT_VALID: 'pageIsNotValid',
  CATEGORY_IS_NOT_VALID: 'categoryIsNotValid',
  PARENT_IS_NOT_VALID: 'parentIsNotValid',
  CHILD_IS_NOT_VALID: 'childIsNotValid',
  STATUS_IS_NOT_VALID: 'statusIsNotValid',
  FEATURED_IMAGE_NOT_VALID: 'featuredImageIsNotValid',
  ROLE_IS_NOT_VALID: 'roleIsNotValid',
  SUPERADMIN_IS_NOT_ALLOWED: 'superAdminIsNotAllowed',
  INCLUDE_IS_NOT_VALID: 'includeIsNotValid',
  COLUMN_IS_NOT_VALID: 'columnIsNotValid',
  TITLE_MUST_BE_UNIQUE: 'titleMustBeUnique',
  SLUG_MUST_BE_UNIQUE: 'slugMustBeUnique',
} as const;
