services:
  db:
    image: postgres:17-alpine
    profiles:
      - dev
    container_name: postgres-dev
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - '${DATABASE_PORT:-5432}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mail:
    image: axllent/mailpit:latest
    profiles:
      - dev
    container_name: mailpit-dev
    ports:
      - '${MAIL_PORT:-1025}:1025'
      - '${MAIL_CLIENT_PORT:-8025}:8025'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    profiles:
      - prod
    platform: ${PLATFORM}
    container_name: nest-app
    environment:
      - NODE_ENV
      - APP_NAME
      - APP_PORT
      - APP_FALLBACK_LANGUAGE
      - APP_HEADER_LANGUAGE
      - FRONTEND_DOMAIN
      - BACKEND_DOMAIN
      - PLATFORM

      - ADMIN_NAME
      - ADMIN_PASSWORD
      - ADMIN_EMAIL
      - AUTH_JWT_SECRET
      - AUTH_JWT_TOKEN_EXPIRES_IN
      - AUTH_REFRESH_SECRET
      - AUTH_REFRESH_TOKEN_EXPIRES_IN

      - DATABASE_TYPE
      - DATABASE_HOST
      - DATABASE_PORT
      - DATABASE_USERNAME
      - DATABASE_PASSWORD
      - DATABASE_NAME
      - DATABASE_SYNCHRONIZE
      - DATABASE_MAX_CONNECTIONS
      - DATABASE_SSL_ENABLED
      - DATABASE_REJECT_UNAUTHORIZED
      - DATABASE_CA
      - DATABASE_KEY
      - DATABASE_CERT

      - MAIL_HOST
      - MAIL_PORT
      - MAIL_USER
      - MAIL_PASSWORD
      - MAIL_IGNORE_TLS
      - MAIL_SECURE
      - MAIL_REQUIRE_TLS
      - MAIL_DEFAULT_EMAIL
      - MAIL_DEFAULT_NAME
      - MAIL_CLIENT_PORT
      - REJECT_UNAUTHORIZED

      - FILE_STORAGE_DRIVER
      - FILE_S3_ENDPOINT
      - FILE_S3_BUCKET
      - FILE_S3_REGION
      - FILE_S3_ACCESS_KEY
      - FILE_S3_SECRET_KEY
      - FILE_S3_PUBLIC_URL
      - FILE_S3_FORCE_PATH_STYLE
      - FILE_MAX_SIZE
    ports:
      - '${APP_PORT}:${APP_PORT}'
    volumes:
      - ./src:/app/src
      - uploads:/app/uploads
    networks:
      - coolify
volumes:
  uploads:
  postgres_data:

networks:
  coolify:
    external: true