services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    platform: ${PLATFORM}
    container_name: nest-app
    environment:
      - PORT=${APP_PORT}
    ports:
      - '${APP_PORT}:5000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
      - uploads:/app/uploads

  db:
    image: mysql:latest
    platform: ${PLATFORM}
    restart: always
    container_name: nest-db
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - ${DATABASE_INNER_PORT}:3306
volumes:
  uploads: