services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    platform: ${PLATFORM}
    container_name: nest-app-${NODE_ENV}
    environment:
      - PORT=${APP_PORT}
    ports:
      - '${APP_PORT}:5000'
    volumes:
      - ./src:/app/src
      - uploads:/app/uploads
volumes:
  uploads: