version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      platform: linux/arm64
    container_name: nest-docker-postgres
    environment:
      - PORT=${PORT}
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src

  db:
    image: mysql:latest
    platform: linux/arm64
    restart: always
    environment:
      MYSQL_DATABASE: vethealth
      MYSQL_PASSWORD: dsdasdasda
      MYSQL_ROOT_PASSWORD: dsdasdasda
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/arm64
    restart: always
    container_name: nest-phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: dsdasdasda
    ports:
      - '8081:80'
    depends_on:
      - db
